[package]
name = "rust_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["syntect", "image"] }
env_logger = "0.11.8"
syntect = "5.3.0"
